name: Trigger Jenkins Job on Label Change

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  trigger-jenkins-job:
    runs-on: windows-latest

    steps:
      - name: Check if label is changed
        id: label_changed
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const labelChanged = labels.includes('merged');

            return { labelChanged: labelChanged };

      - name: Trigger Jenkins Job
        env:
          JENKINS_API_TOKEN: '110762353b227d09d0fcfd22f1b87d99e7'
          JENKINS_JOB_URL: 'https://fifty-jeans-create.loca.lt/job/CCIF_task_1/'
        run: |
          curl -I -u BuildUser:110762353b227d09d0fcfd22f1b87d99e7 "https://fifty-jeans-create.loca.lt/job/CCIF_task_1/build?token=110762353b227d09d0fcfd22f1b87d99e7"
