name: Trigger Jenkins Job on Label Change

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  trigger-jenkins-job:
    runs-on: windows-latest

    steps:
      - name: Check if label is changed
        id: label_changed
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const labelChanged = labels.includes('merged');

            return { labelChanged: labelChanged };

      - name: Trigger Jenkins Job
        if: steps.label_changed.outputs.labelChanged
        env:
          JENKINS_API_TOKEN: '110762353b227d09d0fcfd22f1b87d99e7'
          JENKINS_JOB_URL: 'https://nice-hoops-vanish.loca.lt/job/CCIF_task_1/'
        run: |
          Invoke-WebRequest -Method POST -Uri $env:JENKINS_JOB_URL -Headers @{ Authorization = "Basic $env:JENKINS_API_TOKEN" }
